# Generated by Django 4.2.16 on 2025-01-27 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_alter_recipe_ingredients'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'подписка пользователя', 'verbose_name_plural': 'Подписки пользователя'},
        ),
    ]
