# Generated by Django 4.2.16 on 2025-01-27 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_alter_subscription_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ('user',), 'verbose_name': 'подписка пользователя', 'verbose_name_plural': 'Подписки пользователя'},
        ),
    ]
