# Generated by Django 4.2.16 on 2025-01-27 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_alter_subscription_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
