# Generated by Django 4.2.16 on 2024-11-11 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_tag_slug_ingredientinrecipe_recipe_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.DeleteModel(
            name='IngredientInRecipe',
        ),
    ]
